name: Playwright CI/CD Pipeline
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Automation Code
      uses: actions/checkout@v4

    - name: Checkout Banking Application (Target)
      uses: actions/checkout@v4
      with:
        repository: cypress-io/cypress-realworld-app
        path: cypress-realworld-app

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Yarn
      run: npm install -g yarn

    - name: Patch Banking App for Node Compatibility
      # We need to allow Node >=20 strictly like we did locally
      run: |
        cd cypress-realworld-app
        sed -i 's/"node": ">=.*"/"node": ">=20.0.0"/' package.json
        cat package.json | grep engines -A 3

    - name: Install Banking App Dependencies
      run: |
        cd cypress-realworld-app
        yarn install --network-timeout 1000000 


    - name: Install Playwright Dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run Playwright Tests
      # This will now run BOTH auth.spec.js (UI) and api.spec.js (Engine)
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
